name = "SVGDirect"
uuid = "45d1965d-e861-4fdf-a1cd-40b154fe3189"
authors = ["Jingyue Wang <wang.jingyue@qq.com> and contributors"]
version = "0.1.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
julia = "1"
OrderedCollections = "1.4.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
